# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96bc4dd33917db3185511380e2bd0d134e7e8d3ad3910e206b1ca6167572da52865b6fb6c43b8ebc14d5cdb6318d0316d6aa081189989f5155490cca9adc0d70

test:
  secret_key_base: 12d94795bf4c4612a5c0c178b36670e8b71f7bc0623aa7f4f9222000e2673236d3c79714a209c2805a95de58db5739a177137001d24de635f2bd8287093b90a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
